version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    expose:
      - 80/tcp
    ports:
      - 8001:80
    restart: always
    volumes:
      - ./src:/var/www/html:delegated
      - ./conf/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php
      - mysql
      - redis
      - rabbitmq
    networks:
      - diploma-network
  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php-container
    restart: always
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - diploma-network
  npm:
    build:
      context: ./docker
      dockerfile: npm.dockerfile
    container_name: npm-container
    volumes:
      - ./src:/var/www/html
    networks:
      - diploma-network
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    container_name: composer-container
    volumes:
      - ./src:/var/www/html
    networks:
      - diploma-network
  mysql:
    image: mysql
    container_name: mysql-container
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    depends_on:
      - phpmyadmin
    networks:
      - diploma-network
  redis:
    image: redis
    container_name: redis-container
    expose:
      - 6379/tcp
    ports:
      - 6379:6379
    restart: always
    networks:
      - diploma-network
  rabbitmq:
    build:
      context: ./docker
      dockerfile: ./rabbitmq.dockerfile
    container_name: rabbitmq-container
    expose:
      - 15672/tcp
    ports:
      - 15672:15672
    restart: always
    #    volumes:
    #      - ./rabbitmq:/var/lib/rabbitmq
    env_file:
      - ./env/rabbitmq.env
    networks:
      - diploma-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    expose:
      - 80/tcp
    ports:
      - 8081:80
    restart: always
    env_file:
      - ./env/phpmyadmin.env
    networks:
      - diploma-network

networks:
  diploma-network:
    name: diploma-network
    driver: bridge