version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    expose:
      - 80/tcp
    ports:
      - 8001:80
    restart: always
    volumes:
      - ./:/var/www/app:delegated
      - ../conf/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
      - redis
      - rabbitmq
    networks:
      - dev-network
  php:
    build:
      context: ../docker
      dockerfile: ../docker/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php-container
    restart: always
    volumes:
      - ./:/var/www/app:delegated
      - ../conf/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
    networks:
      - dev-network
  npm:
    build:
      context: ../docker
      dockerfile: ../docker/npm.dockerfile
    container_name: npm-container
    volumes:
      - ./:/var/www/app
    networks:
      - dev-network
  mysql:
    image: mysql
    container_name: mysql-container
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ../database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - phpmyadmin
    networks:
      - dev-network
  redis:
    image: redis
    container_name: redis-container
    expose:
      - 6379/tcp
    ports:
      - 6379:6379
    restart: always
    networks:
      - dev-network
  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq-container
    hostname: rabbitmq
    expose:
      - 15672/tcp
    ports:
      - 15672:15672
    restart: always
    volumes:
      - ../rabbitmq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
     - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    networks:
      - dev-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    expose:
      - 80/tcp
    ports:
      - 8081:80
    restart: always
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge
