version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx-container
    expose:
      - 80/tcp
      - 443/tcp
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./:/var/www/app:delegated
      - ../conf/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ../conf/nginx/ca.crt:/etc/nginx/conf.d/ca.crt:ro
      - ../conf/nginx/trudnyj-vybor.ru.crt:/etc/nginx/conf.d/trudnyj-vybor.ru.crt:ro
      - ../conf/nginx/trudnyj-vybor.ru.key:/etc/nginx/conf.d/trudnyj-vybor.ru.key:ro
    depends_on:
      - php
      - mysql
      - redis
      - rabbitmq
    networks:
      - prod-network

  php:
    build:
      context: ../docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php-container
    restart: always
    volumes:
      - ./:/var/www/app:delegated
    networks:
      - prod-network

  npm:
    build:
      context: ../docker
      dockerfile: ../docker/npm.dockerfile
    container_name: npm-container
    volumes:
      - ./:/var/www/app
    networks:
      - prod-network

  mysql:
    image: mysql
    container_name: mysql-container
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ../database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - phpmyadmin
    networks:
      - prod-network

  redis:
    image: redis
    container_name: redis-container
    expose:
      - 6379/tcp
    ports:
      - 6379:6379
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - prod-network

  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq-container
    hostname: rabbitmq
    expose:
      - 15672/tcp
    ports:
      - 15672:15672
    restart: always
    volumes:
      - ../rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    networks:
      - prod-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    expose:
      - 80/tcp
    ports:
      - 8000:80
    restart: always
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    networks:
      - prod-network

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight-container
    expose:
      - 5000/tcp
    ports:
      - 8082:5540
    networks:
      - prod-network

networks:
  prod-network:
    name: prod-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
